### ISSUE TITLE
Combat engine bug

### ISSUE THREAD

**Issue by clammy115** [thorbuckwel/Joshor#11]
I have noticed that when I attacked a hob goblin, I died, having -2 health. Not the problem. The problem is when you click View on the hobgoblin, he has identical health. I've tested this as well with the black dragon, similar results.

**Comment by thorbuckwel** [comment]
Yea it still has a lot of work but it is a start. I'll try to get it
working right.

**Comment by clammy115** [comment]
It's a great start. I'm looking to see where this might be an issue right now.

**Comment by clammy115** [comment]
I'm looking in the LivingCreature class, and noticed how you have the current hp setup. I think our problem lies where you have this line in Monster.cs:

22 - public Monster(int id, string name, int xp, int gold, int armor, int dam, int ba, int currentHitpoints, int maximumHitpoints, string image, bool isDead) 
            : base(currentHitpoints, maximumHitpoints, isDead)

I know that the monster is only inheriting base values from living creature, but I think this is why the program is considering the player and creature to have the same hp. I'm going to try to add a property for current hp to both the player and the monster, instead of passing it in the constructor.

**Comment by clammy115** [comment]
Before making these changes to the program, I'm gonna email Mr. Norris

**Comment by clammy115** [comment]
After doing some thinking about it, I think we need to move the CurrentHitPoints property to the player/monster class, but leave the maximum hit points in the LivingCreature class.

**Comment by thorbuckwel** [comment]
Alright, Well I'm cutting the thinking cap off tonight. can't really do any
more. My deathscreen pops up when the creature dies also so I think your
right how I can't check the creature hp since it is removed from the cbo
when it is dead.

**Comment by clammy115** [comment]
I discovered another bug, which you may have fixed if you made any changes since your push earlier this evening. In the monster info panel, it displays a goblin's armor class as 16, even though it says 6 in the text file. And when I go to strike the goblin, I rolled a 10 on my hit, so that should have hit him, assuming his armor class was actually 6. I'll look into this a bit more.

**Comment by thorbuckwel** [comment]
Most of the combat problems are fixed however there seems to be a problem with comparing attack with ac because some times we miss even though we meet or exceed the ac of the enemy.
